spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_processor
    username: appuser
    password: apppass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      group-id: order-processor-group
      auto-offset-reset: earliest

  jackson:
    serialization:
      write-dates-as-timestamps: false

kafka:
  topics:
    order-events: order-events
    order-created: order-created
    order-processed: order-processed
    order-failed: order-failed
    order-pending-approval: order-pending-approval

order-processing:
  high-value-threshold: 10000.00
  fraud-threshold: 20000.00
