spring:
  application:
    name: order_processor

  datasource:
    url:
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:}

    consumer:
      group-id: order-processor-group
      auto-offset-reset: earliest

  jackson:
    serialization:
      write-dates-as-timestamps: false

kafka:
  topics:
    order-events: order-events
    order-created: order-created
    order-processed: order-processed
    order-failed: order-failed

order-processing:
  high-value-threshold: 10000.00
  fraud-threshold: 20000.00
